### PR TITLE
Move to Settings

### PR DESCRIPTION
**Pull request by pr0gr8mm3r**
Moves all pages to the settings. This keeps them out of view of regular users and makes it possible to define who can access them via the administrators roles in Enterprise Edition. In Community Edition only super admins can access the pages (which makes sense if you don't want every user to be able to mess up your config :wink:).

### CODE REVIEW

**Comment by ScottAgirs** [comment]
Hey @pr0gr8mm3r thanks for this PR, this looks very cool! 
I tried spinning this up locally, but got an error, here's what I did (please verify that you code changes work, if they do, lmk I'll dig deeper, and once they do I'll review in more detail, but so far really like the idea!)

### **Steps**
```bash
yarn add https://github.com/pr0gr8mm3r/strapi-plugin-migrate/tarball/settings
```

```bash
yarn build:dev --clean && yarn dev
```

Installing and running throws the following error
Screen Shot 2021-05-13 at 10 07 00 AM

**Comment by pr0gr8mm3r** [comment]
Hm, this seems to be on [line 16 in bootstrap.js](https://github.com/ijsto/strapi-plugin-migrate/blob/29b1b6de3289b67a0e15bdf14afbcb67999a0dc1/config/functions/bootstrap.js#L16): I use the name `strapi-plugin-migrate` from the `package.json`, but your folder is probably just `/plugins/migrate` (instead of `/plugins/strapi-plugin-migrate`). I don't know which one of them is the correct name strapi uses if you add the plugin to your project through npm, but I guess it's `strapi-plugin-migrate`. Not sure though...

**Comment by ScottAgirs** [comment]
Hey @pr0gr8mm3r sorry missed your response.

Yeah, I think you're right. I hardcoded the `pluginName: "migrate"` in `bootstrap.js`, however, sadly, the plugin doesn't appear on the siderbar.

Could you please add instruction on how to test this, I as I mentioned, i really like this idea and would love to be able to take it for a spin/merge it.

**Comment by ScottAgirs** [comment]
Awesome, thanks for confirming. 

I'm getting some lots of 404s (screenshot below), I believe this may be caused by the bootstrap name reference. Could you please try to hardcode the name of plugin as `migrate`?

Hopefully, that will solve it.

The last part before merging would be really good is (even if very short) docs/instructions on how the access control can be used. 

Thanks 🙌🏼

Screen Shot 2021-05-17 at 11 36 00 AM

**Comment by pr0gr8mm3r** [comment]
So I hardcoded the plugin name to `migrate` and it now works flawlessly when the folder is called the same.

This however does not fix / answer the question which name will be assumed by strapi once added via npm. See this incredibly cool table of test configurations:

| Type of type               | Name of the folder    | What strapi assumes the name to be | What the plugin name is (in bootstrap.js) | Works                      |
|----------------------------|-----------------------|------------------------------------|-------------------------------------------|----------------------------|
| Local folder No. 1            | migrate               | migrate                            | migrate                                   | Yes                        |
| Local folder No. 2            | strapi-plugin-migrate | strapi-plugin-migrate              | strapi-plugin-migrate                     | Yes                        |
| The initial problem we had | migrate               | migrate                            | strapi-plugin-migrate                     | No                         |
| When used via npm          | N/A                   | I don't know                       | migrate (hardcoded)       | I don't know |

I don't quite know how to deal with that. Release and hope for the best? 😬

**Comment by ScottAgirs** [comment]
Ugh, @pr0gr8mm3r I much appreciate your time and the table looks awesome, haha, thank you for that!

Sadly, it still produces the same error, if you install the tarball of your Fork
Screen Shot 2021-05-19 at 8 57 17 PM

does it now for you?

**Comment by pr0gr8mm3r** [comment]
What's the folder called?

I'm using config "Local folder No. 1" (see table) and it's working great (with sidebars no 404s). I might find time tomorrow to publish the fork on npm for testing.

**Comment by pr0gr8mm3r** [comment]
So I published to npm and it all works as is.

However, there was an issue if you include the forked npm package in an **existing project**:
```
[2021-05-22T11:59:27.424Z] error bootstrap function in plugin "users-permissions" failed
[2021-05-22T11:59:27.426Z] error TypeError: Cannot read property 'id' of null
    at C:\project\node_modules\strapi-plugin-users-permissions\services\UsersPermissions.js:263:59
    at Array.map (<anonymous>)
    at Object.updatePermissions (C:\project\node_modules\strapi-plugin-users-permissions\services\UsersPermissions.js:262:46)
    at async module.exports (C:\project\node_modules\strapi-plugin-users-permissions\config\functions\bootstrap.js:205:3)
    at async Promise.all (index 8)
    at async Strapi.runLifecyclesFunctions (C:\project\node_modules\strapi\lib\Strapi.js:443:5)
    at async Strapi.load (C:\project\node_modules\strapi\lib\Strapi.js:379:5)
    at async Strapi.start (C:\project\node_modules\strapi\lib\Strapi.js:196:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This is the part where strapi loads the existing permissions. Because I obviously can't override the main package on npm strapi gets confused. I am pretty sure that it works when it's the actual, original package. Could you publish an alpha version or something like that? That would help verify that assumption.

**Review by ScottAgirs — APPROVED** [review]
LGTM, thank you @pr0gr8mm3r for the contribution! 🎉

Releasing as `3.6.2`

**Comment by pr0gr8mm3r** [comment]
@ScottAgirs unlike what I expected the issue mentioned in the comment above persists in existing projects. I am working on a fix.

**Comment by ScottAgirs** [comment]
@pr0gr8mm3r by installing from npm registry? 😲 I installed on mine and it seemed to work fine 😬

**Comment by pr0gr8mm3r** [comment]
Hm, interesting. I believe I customized my roles, so it might be because of that. I'll investigate further.

**Comment by pr0gr8mm3r** [comment]
Wasn't able to reproduce this in a test environment, so it seems like a problem of my project setup.

**Comment by ScottAgirs** [comment]
Coolio, will try to monitor this too, perhaps it's time to start considering implementing tests 😅

**Pull request merged**
